# Generated by Django 5.1.1 on 2024-10-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
