# Generated by Django 5.1.1 on 2024-10-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_order_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
